---
# tasks file for temp-bastion
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ cluster_name }}/{{role_name}}/"
    state: directory
    mode: '0755'

- name: Create s3 bucket to store state
  environment:    
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{ region }}"
  amazon.aws.s3_bucket:
    name:  "{{ cluster_name }}-terraform"
    state: present

- name: Copy terraform module to work_dir
  ansible.builtin.copy:
    src: files/
    dest: "{{ work_dir }}/{{ cluster_name }}/{{role_name}}/"

- name: Copy terraform files to work_dir
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ work_dir }}/{{ cluster_name }}/{{role_name}}/{{ item }}"
  with_items:
    - terraform.tfvars.json

- name: "Create bastion"
  environment:
    TF_BACKEND_BUCKET: "{{ cluster_name }}-terraform"
  community.general.terraform:
    project_path: "{{ work_dir }}/{{ cluster_name }}/{{role_name}}/"
    force_init: true
    state: present
  register: bastion_output

- name: "Show output"
  debug:
    msg: "{{bastion_output}}"