---
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ rosa_cluster_name }}/terraform/"
    state: directory
    mode: '0755'

- name: Login to ROSA
  ansible.builtin.command:
    cmd: rosa login --token "{{ rosa_token }}"
  no_log: true
  changed_when: false

- name: Set S3 bucket name
  ansible.builtin.set_fact:
    s3_bucket_name: "{{ rosa_cluster_name }}-terraform"

- name: Create S3 bucket for Terraform state
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    region: "{{ rosa_region }}"
    state: present

- name: Copy terraform files to work_dir
  ansible.builtin.copy:
    src: files/terraform/
    remote_src: false
    dest: "{{ work_dir }}/{{ rosa_cluster_name }}/terraform/"

- name: Template terraform configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ work_dir }}/{{ rosa_cluster_name }}/terraform/{{ item }}"
  loop:
    - terraform.tfvars.json
    - data.tf
    - providers.tf

- name: "Create ROSA HCP cluster: {{ rosa_cluster_name }}"
  cloud.terraform.terraform:
    project_path: "{{ work_dir }}/{{ rosa_cluster_name }}/terraform"
    state: present
    force_init: true
    variables_files:
      - "{{ work_dir }}/{{ rosa_cluster_name }}/terraform/terraform.tfvars.json"
  async: 7200
  poll: 0
  register: create_cluster

- name: "Wait for cluster creation to complete"
  ansible.builtin.async_status:
    jid: "{{ create_cluster.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 240
  delay: 30
